
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE0_CV(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	inout 		          		CLOCK4_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// microSD Card //////////
	output		          		SD_CLK,
	inout 		          		SD_CMD,
	inout 		     [3:0]		SD_DATA
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire [31:0] dec5, dec4, dec3, dec2, dec1, dec0;


//=======================================================
//  Structural coding
//=======================================================

decToSeg_test gg(dec5, dec4, dec3, dec2, dec1, dec0, CLOCK_50);
display g0(HEX0, dec0[3:0]);
display g1(HEX1, dec1[3:0]);
display g2(HEX2, dec2[3:0]);
display g3(HEX3, dec3[3:0]);
display g4(HEX4, dec4[3:0]);
display g5(HEX5, dec5[3:0]);



endmodule
